LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES := chargeled.cpp

LOCAL_CPPFLAGS += -Wall

LOCAL_STATIC_LIBRARIES := libc liblog libcutils
LOCAL_FORCE_STATIC_EXECUTABLE := true

LOCAL_MODULE := chargeled
LOCAL_MODULE_TAGS := optional eng
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_PACK_MODULE_RELOCATIONS := false
include $(BUILD_EXECUTABLE)
